---
abstract: 'Bundle your shared dir into a tarball'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::DZil: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ShareDir-Tarball
provides:
  Dist::Zilla::Plugin::ShareDir::Tarball:
    file: lib/Dist/Zilla/Plugin/ShareDir/Tarball.pm
    version: v0.2.1
requires:
  Archive::Tar: 0
  Compress::Zlib: 0
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileInjector: 0
  Dist::Zilla::Role::FileMunger: 0
  Moose: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-ShareDir-Tarball
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-ShareDir-Tarball/
  repository: https://github.com/yanick/Dist-Zilla-Plugin-ShareDir-Tarball.git
version: 0.2.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
